export const data = [
    {
        id: 1,
        date: "October 2023",
        state: "mumbai",
        title: "Mumbai, Maharashtra",
        description: "Mumbai, the pulsating heart of India, is a city of dreams where tradition and modernity coexist. This sprawling metropolis is known for its iconic skyline, bustling streets, and vibrant cultural tapestry. Home to Bollywood, India's film industry, Mumbai attracts aspiring artists and professionals from all over the country. The city's culinary scene ranges from street food stalls serving delicious vada pav to high-end restaurants offering global cuisines.",
        coverImg: ["mumbai.jpeg", "mumbai1.jpeg", "mumbai2.jpeg", "mumbai3.jpeg", "mumbai4.jpeg", "mumbai5.jpeg"],
        country: "INDIA",
        googleMapLink: "https://www.google.com/maps/place/Mumbai,+Maharashtra/@19.0760,72.8777,11z/data=!3m1!4b1",
    },
    {
        id: 2,
        date: "July 2022",
        state: "goa",
        title: "Goa, India",
        description: "Goa, a serene coastal paradise in India, is celebrated for its stunning beaches, vibrant nightlife, and Portuguese architectural heritage. It offers a unique blend of Eastern and Western traditions, evident in its cuisine, festivals, and daily life. Whether it's the tranquility of South Goa's beaches or the lively parties of North Goa, this city promises a memorable escape for every kind of traveler.",
        coverImg: ["goa.jpeg", "goa1.jpeg", "goa2.jpeg", "goa3.jpeg", "goa4.jpeg", "goa5.jpeg"],
        country: "INDIA",
        googleMapLink: "https://www.google.com/maps/place/Goa/@15.2993,74.1240,10z/data=!3m1!4b1",
    },
    {
        id: 3,
        date: "December 2022",
        state: "delhi",
        title: "Delhi",
        description: "Delhi, where ancient forts whisper tales of empires past amidst the bustling rhythms of modernity. As twilight descends, the city, draped in the golden hues of street lamps, transforms into a poetic enclave where every corner offers an echo of love and history. In Delhi, every breath is a story, and every moment is a crossroad of countless cultures.",
        coverImg: ["delhi.jpeg", "delhi1.jpeg", "delhi2.jpeg", "delhi3.jpeg", "delhi4.jpeg", "delhi5.jpeg"],
        country: "INDIA",
        googleMapLink: "https://www.google.com/maps/place/New+Delhi/@28.6139,77.2090,12z/data=!3m1!4b1",
    },
    {
        id: 4,
        date: "September 2023",
        state: "pondicherry",
        title: "Pondicherry",
        description: "Pondicherry, a serene coastal enclave with a French past, is painted in hues of colonial elegance and spiritual tranquility. Strolling through the charming boulevards lined with bougainvillea, one can savor the quiet blend of Tamil culture and French architecture. The promenade by the sea, echoing with the gentle waves, invites a timeless escape into peace and beauty.",
        coverImg: ["pondicherry.jpeg", "pondicherry6.jpeg", "pondicherry2.jpeg", "pondicherry7.jpeg", "pondicherry4.jpeg", "pondicherry5.jpeg"],
        country: "INDIA",
        googleMapLink: "https://www.google.com/maps/place/Puducherry/@11.9416,79.8083,12z/data=!3m1!4b1",
    },
    {
        id: 5,
        date: "March 2021",
        state: "shimla",
        title: "Shimla",
        description: "Shimla, the queen of hill stations, captivates with its panoramic mountain vistas and colonial-era architecture that whispers stories of a bygone era. Wrapped in a cloak of lush greenery and often draped in winter snow, it offers a picturesque retreat from the hustle of city life. As the narrow gauge railway gently meanders through the hills, Shimla welcomes visitors into its serene embrace, promising an enchanting getaway.",
        coverImg: ["shimla.jpeg", "shimla1.jpeg", "shimla2.jpeg", "shimla3.jpeg", "shimla6.jpeg", "shimla5.jpeg"],
        country: "INDIA",
        googleMapLink: "https://www.google.com/maps/place/Shimla,+Himachal+Pradesh/@31.1048,77.1734,10z/data=!3m1!4b1",
    },
    {
        id: 6,
        date: "May 2018",
        state: "srinagar",
        title: "Jammu and Kashmir",
        description: "Kashmir, often described as heaven on earth, enchants with its breathtaking landscapes of pristine lakes, lush meadows, and snow-capped peaks. Each season paints the valley in a new palette, from vibrant tulip blooms in spring to the serene white of winter snow. The gentle shikaras gliding over Dal Lake capture the tranquil spirit of this timeless land, offering a glimpse into a paradise unspoiled.",
        coverImg: ["jk2.jpeg", "jk1.jpeg", "jk3.jpeg", "jk4.jpeg", "jk5.jpeg", "jk.jpeg"],
        country: "INDIA",
        googleMapLink: "https://www.google.com/maps/place/Jammu+and+Kashmir/@33.2778,75.3412,8z/data=!3m1!4b1",
    },
    {
        id: 7,
        date: "March 2019",
        state: "mauritius",
        title: "Mauritius",
        description: "Mauritius, a jewel in the turquoise waters of the Indian Ocean, beckons with its pristine beaches, lush sugar cane fields, and vibrant coral reefs. The island's rich cultural tapestry, woven from European, African, Indian, and Chinese influences, manifests in its cuisine, music, and festivals. An oasis of peace and multicultural charm, Mauritius offers a serene escape into nature's lap, where every sunset over the ocean seems to promise never-ending tranquility.",
        coverImg: ["mauritius1.jpeg", "mauritius2.jpeg", "mauritius6.jpeg", "mauritius7.jpeg", "mauritius4.jpeg", "mauritius5.jpeg"],
        country: "MAURITIUS",
        googleMapLink: "https://www.google.com/maps/place/Mauritius/@-20.348404,57.552152,10z/data=!3m1!4b1",
    },
    {
        id: 8,
        date: "March 2017",
        state: "assam",
        title: "North East India",
        description: "North East India, nicknamed the 'Seven Sisters', boasts breathtaking diversity. Trek through Arunachal Pradesh's Himalayas, cruise Assam's mighty Brahmaputra River, or marvel at Meghalaya's living root bridges. Immerse yourself in rich tribal cultures, from Manipur's vibrant dance forms to Nagaland's Hornbill Festival. Explore serene temples in Tripura or delve into the mysterious caves of Meghalaya. This region promises adventure, cultural immersion, and unforgettable natural beauty.",
        coverImg: ["northeast2.jpeg","northeast5.jpeg", "northeast3.jpeg", "northeast4.jpeg", "northeast6.jpeg", "northeast7.jpeg"],
        country: "INDIA",
        googleMapLink: "https://www.google.com/maps/place/Northeast+India/@25.700057,92.7088265,7z/data=!3m1!4b1!4m6!3m5!1s0x374f651182a461ab:0xd8b5c2e1f67bebf0!8m2!3d25.5736012!4d93.2472565!16zL20vMDJ2aGow?entry=ttu",
    },
    
];

